### ISSUE TITLE
Consolidate Deno hacks to a centralized place

### ISSUE THREAD

**Issue by ryan-cahill** [architect-team/arcctl#117]
**Is your feature request related to a problem? Please describe.**
Because some Deno -> ESM shims don't work the same way (`existsSync`), we have some hacks scattered across the codebase to fix that. These should be consolidated so that we don't keep writing things that will break down the line.

**Describe the solution you'd like**
* Find a way to make sure that developers know about blacklisted Deno functions up front
* Consolidate Deno function replacements in a util file or something

**Additional context**
Example of problem - https://github.com/architect-team/arcctl/blob/076e11bd2e992638e11de4b8238ce8a009532d49/src/plugins/plugin-manager.ts#L79

**Comment by davidthor** [comment]
The footprint of Deno has shrunk dramatically since deprecating providers, and we no longer have as many hacks. Closing.
