### ISSUE TITLE
Ingress names change if env name is not given

### ISSUE THREAD

**Issue by mueschm** [architect-team/arcctl#145]
**Describe the bug**
When using the `up` command. We create a hash that represents the environment. A PR that went out a bit ago also used the node id to generate a random name for the ingress if one was not provided. This causes a problem though because the node id changes based on the env name. So it is actually not deterministic when using the most basic setup.

**To Reproduce**
1. Run `arcctl up .`
2. Look at any ingress urls
3. Run `arcctl up .` again
4. Notice ingress urls are different

**Expected behavior**
Ingress urls should be deterministic between runs.

**Comment by davidthor** [comment]
I can't reproduce. Are you changing the environment name between up commands?
