### ISSUE TITLE
Add support for serverless datacenter

### ISSUE THREAD

**Issue by mueschm** [architect-team/arcctl#37]
## Description
Currently our system supports EKS deployments for AWS, but we want to be able to support more than on `strategy` per resource per cloud provider. This means that we should also be able to add support for a `deployment` to be done on something besides a Kubernetes cluster. As our first attempt at this we want to use AWS Lambdas.

## Goals
1. Create a new AWS datacenter file that allows us to deploy the `auth` component as is to AWS lambda. The same component should work between all current datacenters and the new one being created.
2. Lambda functions require either a special base container to run or a require a zip file of the programs contents to be used. We need to determine how we want to handle this since it means that a component may need to be updated if we switched datacenters. Our build process currently also only supports containers.

**Comment by davidthor** [comment]
Since providers have been deprecated, this is no longer a core feature of the CLI and instead is in the full control of datacenters. We'll be publishing an example datacenter that uses lambda, but there is no CLI work needed.
