### ISSUE TITLE
Upgrade aws-sdk to aws-sdk-v3

### ISSUE THREAD

**Issue by TylerAldrich** [architect-team/arcctl#55]
The `aws-sdk` dependency is massive (it alone adds ~.2ms to the runtime of every command, and contributes close to 100mb of the compiled binary size). The "v3" of this library has a separate package for each service, which will help us reduce the size of the dependency and improve the speed of the CLI by only using the packages we actually need.

Docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/

**Comment by davidthor** [comment]
No longer relevant since providers have been deprecated and the CLI itself no longer requires the AWS CLI.
